name: Overtone Recipes
description: Programming music with Clojure
meta_description: "Overtone Recipes, programming music with Clojure"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://overtone-recipes.github.io'
google_analytics: 'UA-76046732-1'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://overtone-recipes.github.io'
author:         'Piotr Jagielski'
