name: Live-coding Recipes
description: Programming music with Kotlin and Clojure
meta_description: "Live-coding Recipes, programming music with Kotlin and Clojure"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'http://livecoding-recipes.github.io'
google_analytics: 'UA-76046732-1'
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url:            'http://livecoding-recipes.github.io'
author:         'Piotr Jagielski'
